added moment library, implemeted calendar
pawelwojkiewicz/organizer-app pull request #9
Opened 2021-07-04 13:27 UTC by pawelwojkiewicz

2021-07-05 05:05 UTC, mati4455 requested changes

2021-07-05 05:05 UTC, mati4455 commented on src/app/modules/calendar/components/calendar-tile/calendar-tile.component.scss
> +  width: calc(100% /7 - 10px);
nie lepiej zrobić flexa albo nawet css grida?

2021-07-05 05:05 UTC, mati4455 commented on src/app/modules/calendar/components/header/header.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Proponuje nie wrzucać plikó testówych bez testów - wtedy będziesz wiedział co nie jest otestowane :) bo za dużo jest takich bez testów.

2021-07-06 05:47 UTC, pawelwojkiewicz commented on src/app/modules/calendar/components/calendar-tile/calendar-tile.component.scss
> +  width: calc(100% /7 - 10px);
do przerobienia na końcu przy stylowaniu całej aplikacji

2021-07-06 05:47 UTC, pawelwojkiewicz commented on src/app/modules/calendar/components/header/header.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
done

2021-07-19 06:23 UTC, merged